FROM docker.elastic.co/elasticsearch/elasticsearch:8.19.1 
USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create virtual environment and activate it in order to avoid the “externally managed Python” errors for Python 3.12 on Ubuntu
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY scripts/elasticsearch_requirements.txt /tmp/requirements.txt
RUN python3 -m pip install -r /tmp/requirements.txt && rm /tmp/requirements.txt

COPY scripts/elasticsearch-init.py /usr/local/bin/elasticsearch-init.py
COPY scripts/elasticsearch-startup.sh /usr/local/bin/elasticsearch-startup.sh

# Make scripts executable
RUN chmod +x /usr/local/bin/elasticsearch-init.py && \
    chmod +x /usr/local/bin/elasticsearch-startup.sh

USER elasticsearch

ENTRYPOINT ["/usr/local/bin/elasticsearch-startup.sh"]